version: "2"
linters:
  enable:
    - gocyclo
    - revive
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
