run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - gocyclo
    - revive
    - typecheck

issues:
  exclude-use-default: false
  exclude-rules: []
