// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/proto/weather/weather.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherRequest) Reset() {
	*x = GetWeatherRequest{}
	mi := &file_api_proto_weather_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherRequest) ProtoMessage() {}

func (x *GetWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_weather_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherRequest.ProtoReflect.Descriptor instead.
func (*GetWeatherRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_weather_weather_proto_rawDescGZIP(), []int{0}
}

func (x *GetWeatherRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type GetWeatherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weather       *WeatherData           `protobuf:"bytes,1,opt,name=weather,proto3" json:"weather,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherResponse) Reset() {
	*x = GetWeatherResponse{}
	mi := &file_api_proto_weather_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherResponse) ProtoMessage() {}

func (x *GetWeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_weather_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherResponse.ProtoReflect.Descriptor instead.
func (*GetWeatherResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_weather_weather_proto_rawDescGZIP(), []int{1}
}

func (x *GetWeatherResponse) GetWeather() *WeatherData {
	if x != nil {
		return x.Weather
	}
	return nil
}

type GetWeatherBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cities        []string               `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherBatchRequest) Reset() {
	*x = GetWeatherBatchRequest{}
	mi := &file_api_proto_weather_weather_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherBatchRequest) ProtoMessage() {}

func (x *GetWeatherBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_weather_weather_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherBatchRequest.ProtoReflect.Descriptor instead.
func (*GetWeatherBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_weather_weather_proto_rawDescGZIP(), []int{2}
}

func (x *GetWeatherBatchRequest) GetCities() []string {
	if x != nil {
		return x.Cities
	}
	return nil
}

type GetWeatherBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeatherData   []*WeatherData         `protobuf:"bytes,1,rep,name=weather_data,json=weatherData,proto3" json:"weather_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherBatchResponse) Reset() {
	*x = GetWeatherBatchResponse{}
	mi := &file_api_proto_weather_weather_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherBatchResponse) ProtoMessage() {}

func (x *GetWeatherBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_weather_weather_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherBatchResponse.ProtoReflect.Descriptor instead.
func (*GetWeatherBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_weather_weather_proto_rawDescGZIP(), []int{3}
}

func (x *GetWeatherBatchResponse) GetWeatherData() []*WeatherData {
	if x != nil {
		return x.WeatherData
	}
	return nil
}

type GetProviderInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderInfoRequest) Reset() {
	*x = GetProviderInfoRequest{}
	mi := &file_api_proto_weather_weather_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderInfoRequest) ProtoMessage() {}

func (x *GetProviderInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_weather_weather_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderInfoRequest.ProtoReflect.Descriptor instead.
func (*GetProviderInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_weather_weather_proto_rawDescGZIP(), []int{4}
}

type GetProviderInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderInfo  *ProviderInfo          `protobuf:"bytes,1,opt,name=provider_info,json=providerInfo,proto3" json:"provider_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderInfoResponse) Reset() {
	*x = GetProviderInfoResponse{}
	mi := &file_api_proto_weather_weather_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderInfoResponse) ProtoMessage() {}

func (x *GetProviderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_weather_weather_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderInfoResponse.ProtoReflect.Descriptor instead.
func (*GetProviderInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_weather_weather_proto_rawDescGZIP(), []int{5}
}

func (x *GetProviderInfoResponse) GetProviderInfo() *ProviderInfo {
	if x != nil {
		return x.ProviderInfo
	}
	return nil
}

type GetCacheMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheMetricsRequest) Reset() {
	*x = GetCacheMetricsRequest{}
	mi := &file_api_proto_weather_weather_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheMetricsRequest) ProtoMessage() {}

func (x *GetCacheMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_weather_weather_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetCacheMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_weather_weather_proto_rawDescGZIP(), []int{6}
}

type GetCacheMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CacheStats    *CacheStats            `protobuf:"bytes,1,opt,name=cache_stats,json=cacheStats,proto3" json:"cache_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheMetricsResponse) Reset() {
	*x = GetCacheMetricsResponse{}
	mi := &file_api_proto_weather_weather_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheMetricsResponse) ProtoMessage() {}

func (x *GetCacheMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_weather_weather_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetCacheMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_weather_weather_proto_rawDescGZIP(), []int{7}
}

func (x *GetCacheMetricsResponse) GetCacheStats() *CacheStats {
	if x != nil {
		return x.CacheStats
	}
	return nil
}

type WeatherData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   float64                `protobuf:"fixed64,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity      float64                `protobuf:"fixed64,2,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherData) Reset() {
	*x = WeatherData{}
	mi := &file_api_proto_weather_weather_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherData) ProtoMessage() {}

func (x *WeatherData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_weather_weather_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherData.ProtoReflect.Descriptor instead.
func (*WeatherData) Descriptor() ([]byte, []int) {
	return file_api_proto_weather_weather_proto_rawDescGZIP(), []int{8}
}

func (x *WeatherData) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *WeatherData) GetHumidity() float64 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *WeatherData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WeatherData) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *WeatherData) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ProviderInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalProviders  int32                  `protobuf:"varint,1,opt,name=total_providers,json=totalProviders,proto3" json:"total_providers,omitempty"`
	ProviderOrder   []string               `protobuf:"bytes,2,rep,name=provider_order,json=providerOrder,proto3" json:"provider_order,omitempty"`
	ChainEnabled    bool                   `protobuf:"varint,3,opt,name=chain_enabled,json=chainEnabled,proto3" json:"chain_enabled,omitempty"`
	FallbackEnabled bool                   `protobuf:"varint,4,opt,name=fallback_enabled,json=fallbackEnabled,proto3" json:"fallback_enabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_api_proto_weather_weather_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_weather_weather_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_weather_weather_proto_rawDescGZIP(), []int{9}
}

func (x *ProviderInfo) GetTotalProviders() int32 {
	if x != nil {
		return x.TotalProviders
	}
	return 0
}

func (x *ProviderInfo) GetProviderOrder() []string {
	if x != nil {
		return x.ProviderOrder
	}
	return nil
}

func (x *ProviderInfo) GetChainEnabled() bool {
	if x != nil {
		return x.ChainEnabled
	}
	return false
}

func (x *ProviderInfo) GetFallbackEnabled() bool {
	if x != nil {
		return x.FallbackEnabled
	}
	return false
}

type CacheStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          int64                  `protobuf:"varint,1,opt,name=hits,proto3" json:"hits,omitempty"`
	Misses        int64                  `protobuf:"varint,2,opt,name=misses,proto3" json:"misses,omitempty"`
	TotalOps      int64                  `protobuf:"varint,3,opt,name=total_ops,json=totalOps,proto3" json:"total_ops,omitempty"`
	HitRatio      float64                `protobuf:"fixed64,4,opt,name=hit_ratio,json=hitRatio,proto3" json:"hit_ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheStats) Reset() {
	*x = CacheStats{}
	mi := &file_api_proto_weather_weather_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheStats) ProtoMessage() {}

func (x *CacheStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_weather_weather_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheStats.ProtoReflect.Descriptor instead.
func (*CacheStats) Descriptor() ([]byte, []int) {
	return file_api_proto_weather_weather_proto_rawDescGZIP(), []int{10}
}

func (x *CacheStats) GetHits() int64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *CacheStats) GetMisses() int64 {
	if x != nil {
		return x.Misses
	}
	return 0
}

func (x *CacheStats) GetTotalOps() int64 {
	if x != nil {
		return x.TotalOps
	}
	return 0
}

func (x *CacheStats) GetHitRatio() float64 {
	if x != nil {
		return x.HitRatio
	}
	return 0
}

var File_api_proto_weather_weather_proto protoreflect.FileDescriptor

const file_api_proto_weather_weather_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/weather/weather.proto\x12\aweather\x1a\x1fgoogle/protobuf/timestamp.proto\"'\n" +
	"\x11GetWeatherRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\"D\n" +
	"\x12GetWeatherResponse\x12.\n" +
	"\aweather\x18\x01 \x01(\v2\x14.weather.WeatherDataR\aweather\"0\n" +
	"\x16GetWeatherBatchRequest\x12\x16\n" +
	"\x06cities\x18\x01 \x03(\tR\x06cities\"R\n" +
	"\x17GetWeatherBatchResponse\x127\n" +
	"\fweather_data\x18\x01 \x03(\v2\x14.weather.WeatherDataR\vweatherData\"\x18\n" +
	"\x16GetProviderInfoRequest\"U\n" +
	"\x17GetProviderInfoResponse\x12:\n" +
	"\rprovider_info\x18\x01 \x01(\v2\x15.weather.ProviderInfoR\fproviderInfo\"\x18\n" +
	"\x16GetCacheMetricsRequest\"O\n" +
	"\x17GetCacheMetricsResponse\x124\n" +
	"\vcache_stats\x18\x01 \x01(\v2\x13.weather.CacheStatsR\n" +
	"cacheStats\"\xbb\x01\n" +
	"\vWeatherData\x12 \n" +
	"\vtemperature\x18\x01 \x01(\x01R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x02 \x01(\x01R\bhumidity\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xae\x01\n" +
	"\fProviderInfo\x12'\n" +
	"\x0ftotal_providers\x18\x01 \x01(\x05R\x0etotalProviders\x12%\n" +
	"\x0eprovider_order\x18\x02 \x03(\tR\rproviderOrder\x12#\n" +
	"\rchain_enabled\x18\x03 \x01(\bR\fchainEnabled\x12)\n" +
	"\x10fallback_enabled\x18\x04 \x01(\bR\x0ffallbackEnabled\"r\n" +
	"\n" +
	"CacheStats\x12\x12\n" +
	"\x04hits\x18\x01 \x01(\x03R\x04hits\x12\x16\n" +
	"\x06misses\x18\x02 \x01(\x03R\x06misses\x12\x1b\n" +
	"\ttotal_ops\x18\x03 \x01(\x03R\btotalOps\x12\x1b\n" +
	"\thit_ratio\x18\x04 \x01(\x01R\bhitRatio2\xd9\x02\n" +
	"\x0eWeatherService\x12E\n" +
	"\n" +
	"GetWeather\x12\x1a.weather.GetWeatherRequest\x1a\x1b.weather.GetWeatherResponse\x12T\n" +
	"\x0fGetWeatherBatch\x12\x1f.weather.GetWeatherBatchRequest\x1a .weather.GetWeatherBatchResponse\x12T\n" +
	"\x0fGetProviderInfo\x12\x1f.weather.GetProviderInfoRequest\x1a .weather.GetProviderInfoResponse\x12T\n" +
	"\x0fGetCacheMetrics\x12\x1f.weather.GetCacheMetricsRequest\x1a .weather.GetCacheMetricsResponseB\x1aZ\x18weatherapi.app/api/protob\x06proto3"

var (
	file_api_proto_weather_weather_proto_rawDescOnce sync.Once
	file_api_proto_weather_weather_proto_rawDescData []byte
)

func file_api_proto_weather_weather_proto_rawDescGZIP() []byte {
	file_api_proto_weather_weather_proto_rawDescOnce.Do(func() {
		file_api_proto_weather_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_weather_weather_proto_rawDesc), len(file_api_proto_weather_weather_proto_rawDesc)))
	})
	return file_api_proto_weather_weather_proto_rawDescData
}

var file_api_proto_weather_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_weather_weather_proto_goTypes = []any{
	(*GetWeatherRequest)(nil),       // 0: weather.GetWeatherRequest
	(*GetWeatherResponse)(nil),      // 1: weather.GetWeatherResponse
	(*GetWeatherBatchRequest)(nil),  // 2: weather.GetWeatherBatchRequest
	(*GetWeatherBatchResponse)(nil), // 3: weather.GetWeatherBatchResponse
	(*GetProviderInfoRequest)(nil),  // 4: weather.GetProviderInfoRequest
	(*GetProviderInfoResponse)(nil), // 5: weather.GetProviderInfoResponse
	(*GetCacheMetricsRequest)(nil),  // 6: weather.GetCacheMetricsRequest
	(*GetCacheMetricsResponse)(nil), // 7: weather.GetCacheMetricsResponse
	(*WeatherData)(nil),             // 8: weather.WeatherData
	(*ProviderInfo)(nil),            // 9: weather.ProviderInfo
	(*CacheStats)(nil),              // 10: weather.CacheStats
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
}
var file_api_proto_weather_weather_proto_depIdxs = []int32{
	8,  // 0: weather.GetWeatherResponse.weather:type_name -> weather.WeatherData
	8,  // 1: weather.GetWeatherBatchResponse.weather_data:type_name -> weather.WeatherData
	9,  // 2: weather.GetProviderInfoResponse.provider_info:type_name -> weather.ProviderInfo
	10, // 3: weather.GetCacheMetricsResponse.cache_stats:type_name -> weather.CacheStats
	11, // 4: weather.WeatherData.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 5: weather.WeatherService.GetWeather:input_type -> weather.GetWeatherRequest
	2,  // 6: weather.WeatherService.GetWeatherBatch:input_type -> weather.GetWeatherBatchRequest
	4,  // 7: weather.WeatherService.GetProviderInfo:input_type -> weather.GetProviderInfoRequest
	6,  // 8: weather.WeatherService.GetCacheMetrics:input_type -> weather.GetCacheMetricsRequest
	1,  // 9: weather.WeatherService.GetWeather:output_type -> weather.GetWeatherResponse
	3,  // 10: weather.WeatherService.GetWeatherBatch:output_type -> weather.GetWeatherBatchResponse
	5,  // 11: weather.WeatherService.GetProviderInfo:output_type -> weather.GetProviderInfoResponse
	7,  // 12: weather.WeatherService.GetCacheMetrics:output_type -> weather.GetCacheMetricsResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_weather_weather_proto_init() }
func file_api_proto_weather_weather_proto_init() {
	if File_api_proto_weather_weather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_weather_weather_proto_rawDesc), len(file_api_proto_weather_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_weather_weather_proto_goTypes,
		DependencyIndexes: file_api_proto_weather_weather_proto_depIdxs,
		MessageInfos:      file_api_proto_weather_weather_proto_msgTypes,
	}.Build()
	File_api_proto_weather_weather_proto = out.File
	file_api_proto_weather_weather_proto_goTypes = nil
	file_api_proto_weather_weather_proto_depIdxs = nil
}
