name: Architecture Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  architecture-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-arch-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-arch-

    - name: Install go-arch-lint
      run: go install github.com/fe3dback/go-arch-lint@latest

    - name: Run architecture tests
      run: |
        echo "Running architecture validation..."
        go-arch-lint check

    - name: Generate architecture graph
      run: |
        echo "Generating architecture dependency graph..."
        mkdir -p docs
        go-arch-lint graph --out=docs/architecture-graph.svg

    - name: Upload architecture graph
      uses: actions/upload-artifact@v4
      with:
        name: architecture-graph
        path: docs/architecture-graph.svg
        retention-days: 30

    - name: Comment PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Check if architecture graph exists
          const graphPath = 'docs/architecture-graph.svg';
          const graphExists = fs.existsSync(graphPath);
          
          let body = '## 🏗️ Architecture Tests Results\n\n';
          body += '✅ **Architecture validation passed!**\n\n';
          body += 'Your code follows the hexagonal architecture dependency rules:\n';
          body += '- Domain layer has no external dependencies\n';
          body += '- Ports layer depends only on domain\n';
          body += '- Adapters depend on ports and domain\n';
          body += '- Application layer coordinates all components\n\n';
          
          if (graphExists) {
            body += '📊 **Architecture dependency graph generated** - Check the artifacts section for the visual representation.\n\n';
          }
          
          body += '---\n';
          body += '*This comment was automatically generated by the architecture tests workflow.*';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
