name: Integration Tests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-integration-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-integration-

    - name: Run integration tests
      run: make -f Makefile.testing test-integration
